# Generated by Django 3.0.5 on 2020-04-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
    ]
